<?php

declare(strict_types=1);
/**
 * This file is part of MineAdmin.
 *
 * @link     https://www.mineadmin.com
 * @document https://doc.mineadmin.com
 * @contact  root@imoi.cn
 * @license  https://github.com/mineadmin/MineAdmin/blob/master/LICENSE
 */
$code = '';
return [
    'groups' => [
        'basic' => [
            'label' => '基础信息',
            'description' => '商城通用基础资料与多语言设置。',
            'sort' => 10,
            'settings' => [
                'mall.basic.name' => [
                    'label' => '商城名称',
                    'description' => '展示在前台、邮件以及通知中的商城名称。',
                    'type' => 'string',
                    'default' => 'MineMall 商城',
                    'sort' => 10,
                ],
                'mall.basic.admin_logo' => [
                    'label' => '后台管理 Logo',
                    'description' => '后台管理系统侧边栏 Logo，建议 200×50 透明底 PNG/SVG。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 72,
                    ],
                    'default' => '/logo.svg',
                    'sort' => 15,
                ],
                'mall.basic.admin_small_logo' => [
                    'label' => '后台管理小 Logo',
                    'description' => '侧边栏收起状态下的显示，建议 32×32 透明底 PNG/SVG。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 40,
                    ],
                    'default' => '/logo.svg',
                    'sort' => 16,
                ],
                'mall.basic.login_logo' => [
                    'label' => '登录页 Logo',
                    'description' => '后台登录页面显示的 Logo，建议 200×50 透明底 PNG/SVG。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 72,
                    ],
                    'default' => '/logo.svg',
                    'sort' => 17,
                ],
                'mall.basic.miniapp_logo' => [
                    'label' => '小程序 Logo',
                    'description' => '小程序端使用的商城图标，建议 1:1 比例。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 52,
                    ],
                    'default' => '',
                    'sort' => 18,
                ],
                'mall.basic.favicon' => [
                    'label' => '网站 Favicon',
                    'description' => '浏览器标签栏图标，建议 32×32 ICO/PNG 格式。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 32,
                    ],
                    'default' => '/favicon.ico',
                    'sort' => 19,
                ],
                // 保留原有 logo 配置作为兼容
                'mall.basic.logo' => [
                    'label' => '商城通用 Logo',
                    'description' => '用于小程序首页备用、分享图标等通用场景。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 52,
                    ],
                    'default' => '/logo.svg',
                    'sort' => 20,
                ],
                // 语言与时区相关能力暂不开放
                'mall.basic.user_agreement' => [
                    'label' => '用户协议',
                    'description' => 'H5 注册页用于展示的用户协议内容。',
                    'type' => 'text',
                    'meta' => [
                        'display_span' => ['wide'],
                    ],
                    'default' => '欢迎您使用 MineMall 商城服务。用户在注册、登录及使用本平台服务前，应当仔细阅读并同意本协议全部内容。用户完成注册后，即视为已具备相应民事行为能力，并同意遵守平台关于商品浏览、下单支付、售后服务、账号安全及内容发布等相关规则。用户应妥善保管账号信息，不得将账号出借、转让或用于任何违法违规用途；因用户自身原因造成的账号泄露、交易风险或损失，由用户自行承担。平台有权在法律法规允许范围内对服务内容、活动规则及协议条款进行调整，并通过站内公告或页面公示方式通知用户。',
                    'sort' => 90,
                ],
                'mall.basic.privacy_policy' => [
                    'label' => '隐私政策',
                    'description' => 'H5 注册页用于展示的隐私政策内容。',
                    'type' => 'text',
                    'meta' => [
                        'display_span' => ['wide'],
                    ],
                    'default' => 'MineMall 重视您的个人信息与隐私安全。为了向您提供注册登录、商品购买、订单履约、售后服务及通知提醒等功能，我们可能会收集您的手机号、账号信息、收货信息、订单信息及设备基础信息，并仅在提供服务、保障交易安全、优化体验及符合法律法规要求的范围内使用。未经您的明确同意，我们不会将您的个人信息用于与本平台服务无关的用途，也不会向无关第三方出售您的个人信息。您有权依法查阅、更正、删除相关信息，并可通过平台客服与我们联系。我们将采取合理的技术与管理措施保护您的信息安全。',
                    'sort' => 95,
                ],
                'mall.basic.support_email' => [
                    'label' => '客服邮箱',
                    'description' => '用于系统通知与工单回复的官方邮箱。',
                    'type' => 'string',
                    'default' => 'support@minemall.local',
                    'sort' => 50,
                ],
                'mall.basic.hotline' => [
                    'label' => '客服电话',
                    'description' => '前台展示与短信通知使用的联系电话。',
                    'type' => 'string',
                    'default' => '400-888-0000',
                    'sort' => 60,
                ],
                'mall.home.banners' => [
                    'label' => '首页 Banner 图',
                    'description' => '用于小程序/前台首页轮播，建议 3-6 张，按顺序展示。',
                    'type' => 'json',
                    'meta' => [
                        'component' => 'collection',
                        'display_span' => ['compact'],
                        'display' => 'dialog',
                        'button_label' => '配置 Banner',
                        'add_label' => '新增 Banner',
                        'min_items' => 3,
                        'max_items' => 6,
                        'fields' => [
                            [
                                'key' => 'image',
                                'label' => '图片地址',
                                'placeholder' => 'https://example.com/banner.png',
                                'required' => true,
                            ],
                            [
                                'key' => 'link',
                                'label' => '跳转链接',
                                'placeholder' => 'https://example.com/page',
                            ],
                        ],
                    ],
                    'default' => [],
                    'sort' => 70,
                ],
                'mall.home.activity_banner' => [
                    'label' => '首页活动图',
                    'description' => '首页活动卡片/运营位图片，建议 750×320，留空则回退到商城 LOGO。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 84,
                    ],
                    'default' => '',
                    'sort' => 80,
                ],
                'mall.seckill.topic_banner' => [
                    'label' => '秒杀活动图',
                    'description' => '秒杀活动卡片/运营位图片，建议 750×320，留空则回退到商城 LOGO。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'upload',
                        'display_span' => ['compact'],
                        'preview_size' => 84,
                    ],
                    'default' => 'https://oss.mineshop.club/2026-04-02/2d8db190-60fc-4e43-9316-2086859df76e.png',
                    'sort' => 80,
                ],
            ],
        ],
        'integration' => [
            'label' => '系统集成',
            'description' => '消息通知、第三方服务与站点安全能力。',
            'sort' => 30,
            'settings' => [
                'mall.integration.sms_provider' => [
                    'label' => '短信服务商',
                    'description' => '用于登录验证码、订单提醒等短信。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'select',
                        'options' => [
                            ['label' => '阿里云短信', 'value' => 'aliyun'],
                            ['label' => '腾讯云短信', 'value' => 'tencent'],
                            ['label' => '云片短信', 'value' => 'yunpian'],
                            ['label' => '关闭短信', 'value' => 'disabled'],
                        ],
                    ],
                    'default' => 'aliyun',
                    'sort' => 10,
                ],
                'mall.integration.sms_config' => [
                    'label' => '短信配置',
                    'description' => '填写短信服务所需的密钥信息，系统自动生成 JSON 配置。',
                    'type' => 'json',
                    'is_sensitive' => true,
                    'meta' => [
                        'component' => 'form',
                        'display' => 'dialog',
                        'trigger_key' => 'mall.integration.sms_provider',
                        'trigger_not_value' => 'disabled',
                        'button_label' => '配置参数',
                        'fields' => [
                            [
                                'key' => 'access_key_id',
                                'label' => 'AccessKey ID',
                                'placeholder' => '请输入 AccessKey ID',
                            ],
                            [
                                'key' => 'access_key_secret',
                                'label' => 'AccessKey Secret',
                                'placeholder' => '请输入 AccessKey Secret',
                                'input_type' => 'password',
                            ],
                            [
                                'key' => 'sign_name',
                                'label' => '短信签名',
                                'placeholder' => '请输入短信签名',
                            ],
                            [
                                'key' => 'template_code',
                                'label' => '默认模板 CODE',
                                'placeholder' => '可选，传入默认模板编号',
                            ],
                            [
                                'key' => 'template_param_key',
                                'label' => '模板变量名',
                                'placeholder' => '与阿里云模板中 ${xxx} 的 xxx 一致，如 code、number',
                            ],
                        ],
                    ],
                    'default' => [
                        'access_key_id' => '',
                        'access_key_secret' => '',
                        'sign_name' => '',
                        'template_code' => '',
                        'template_param_key' => 'code',
                    ],
                    'sort' => 20,
                ],
                'mall.integration.notif_channels' => [
                    'label' => '系统通知渠道',
                    'description' => '控制订单/库存/售后等通知的渠道。',
                    'type' => 'json',
                    'meta' => [
                        'component' => 'form',
                        'layout' => 'inline',
                        'display_span' => ['compact'],
                        'fields' => [
                            [
                                'key' => 'mail',
                                'label' => '邮件通知',
                                'component' => 'switch',
                            ],
                            [
                                'key' => 'sms',
                                'label' => '短信通知',
                                'component' => 'switch',
                            ],
                            [
                                'key' => 'system',
                                'label' => '站内通知',
                                'component' => 'switch',
                            ],
                        ],
                    ],
                    'default' => [
                        'mail' => true,
                        'sms' => false,
                        'system' => true,
                    ],
                    'sort' => 30,
                ],
                'mall.integration.sms_template' => [
                    'label' => '短信验证码模板',
                    'description' => '站内展示用，支持 {{$code}} 等；须与「配置参数」里模板变量名一致（如阿里云为 ${number} 则写 {{$number}}）。',
                    'type' => 'input',
                    'meta' => [
                        'display_span' => ['compact'],
                    ],
                    'default' => '【MineMall】您的验证码为{{$code}}，请勿泄露给他人。',
                    'sort' => 35,
                ],
                'mall.integration.email_template' => [
                    'label' => '邮件通知模板',
                    'description' => '支持变量 {{$subject}}、{{$content}}、{{$code}} 等，请根据业务自定义 HTML 文案。',
                    'type' => 'text',
                    'meta' => [
                        'display_span' => ['compact'],
                    ],
                    'default' => "<p>亲爱的用户：</p><p>您的验证码为 <strong>{{$code}}</strong>，5 分钟内有效。</p><p>感谢使用 MineMall。</p>",
                    'sort' => 37,
                ],
                'mall.integration.webhook_url' => [
                    'label' => '运营 Webhook',
                    'description' => '用于推送重大事件（如库存预警）的第三方回调地址。',
                    'type' => 'string',
                    'default' => '',
                    'sort' => 40,
                ],
                'mall.integration.audit_mode' => [
                    'label' => '安全审核模式',
                    'description' => '开启后新增接口需经安全审批，适合准生产环境。',
                    'type' => 'boolean',
                    'default' => false,
                    'sort' => 50,
                ],
            ],
        ],
        'product' => [
            'label' => '商品与库存',
            'description' => '商品发布限制、库存安全以及内容控制。',
            'sort' => 40,
            'settings' => [
                'mall.product.auto_generate_sku' => [
                    'label' => '自动生成 SKU',
                    'description' => '关闭后新增商品必须手动录入 SKU 编码。',
                    'type' => 'boolean',
                    'default' => true,
                    'sort' => 10,
                ],
                'mall.product.max_gallery' => [
                    'label' => '商品主图数量上限',
                    'description' => '单个商品允许上传的主图数量。',
                    'type' => 'integer',
                    'default' => 9,
                    'sort' => 20,
                ],
                'mall.product.stock_warning' => [
                    'label' => '库存预警线',
                    'description' => '当 SKU 库存低于该值时触发预警。',
                    'type' => 'integer',
                    'default' => 20,
                    'sort' => 30,
                ],
                'mall.product.allow_preorder' => [
                    'label' => '允许预售商品',
                    'description' => '开启后可发布预售商品，系统自动管控尾款时间。',
                    'type' => 'boolean',
                    'default' => false,
                    'sort' => 40,
                ],
                'mall.product.content_filter' => [
                    'label' => '敏感词过滤',
                    'description' => '用于限制商品标题、详情中出现的违规词，换行分隔。',
                    'type' => 'text',
                    'default' => "违法\n侵权\n仿品",
                    'sort' => 50,
                ],
            ],
        ],
        'order' => [
            'label' => '订单与售后',
            'description' => '订单生命周期、风控及售后配置。',
            'sort' => 50,
            'settings' => [
                'mall.order.auto_close_minutes' => [
                    'label' => '未支付自动关闭',
                    'description' => '订单在多少分钟未支付将自动关闭。',
                    'type' => 'integer',
                    'default' => 30,
                    'sort' => 10,
                ],
                'mall.order.auto_confirm_days' => [
                    'label' => '发货自动完成',
                    'description' => '发货后多少天自动确认收货。',
                    'type' => 'integer',
                    'default' => 7,
                    'sort' => 20,
                ],
                'mall.order.after_sale_days' => [
                    'label' => '售后受理期',
                    'description' => '签收后允许申请售后的天数。',
                    'type' => 'integer',
                    'default' => 15,
                    'sort' => 30,
                ],
                'mall.order.enable_invoice' => [
                    'label' => '启用发票服务',
                    'description' => '控制系统是否支持用户开票申请。',
                    'type' => 'boolean',
                    'default' => true,
                    'sort' => 40,
                ],
                'mall.order.invoice_provider' => [
                    'label' => '发票开具方式',
                    'description' => '自营或第三方服务平台。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'select',
                        'options' => [
                            ['label' => '系统自营', 'value' => 'system'],
                            ['label' => '航信云', 'value' => 'vatcloud'],
                            ['label' => '自定义方案', 'value' => 'custom'],
                        ],
                    ],
                    'default' => 'system',
                    'sort' => 50,
                ],
                'mall.order.customer_service' => [
                    'label' => '售后联系电话',
                    'description' => '售后单短信通知中会展示该号码。',
                    'type' => 'string',
                    'default' => '400-888-1000',
                    'sort' => 60,
                ],
            ],
        ],
        'payment' => [
            'label' => '支付与结算',
            'description' => '支付方式及风控策略，满足微信/钱包支付退款。',
            'sort' => 60,
            'settings' => [
                'mall.payment.wechat_enabled' => [
                    'label' => '启用微信支付',
                    'description' => '微信 JSAPI/小程序/APP 支付统一开关。',
                    'type' => 'boolean',
                    'default' => false,
                    'sort' => 10,
                ],
                'mall.payment.wechat_config' => [
                    'label' => '微信支付配置',
                    'description' => '遵循 yansongda/pay 配置结构的 JSON 数据。',
                    'type' => 'json',
                    'is_sensitive' => true,
                    'meta' => [
                        'component' => 'form',
                        'display' => 'dialog',
                        'trigger_key' => 'mall.payment.wechat_enabled',
                        'trigger_value' => true,
                        'button_label' => '密钥设置',
                        'fields' => [
                            [
                                'key' => 'mchid',
                                'label' => '商户号 MCHID',
                                'placeholder' => '请输入微信支付商户号',
                                'required' => true,
                            ],
                            [
                                'key' => 'app_id',
                                'label' => 'AppID',
                                'placeholder' => '请输入公众号/小程序 AppID',
                                'required' => true,
                            ],
                            [
                                'key' => 'serial_no',
                                'label' => '证书序列号',
                                'placeholder' => '请输入证书序列号',
                                'required' => true,
                            ],
                            [
                                'key' => 'private_key',
                                'label' => '商户私钥',
                                'component' => 'textarea',
                                'rows' => 4,
                                'placeholder' => '-----BEGIN PRIVATE KEY-----',
                                'required' => true,
                            ],
                            [
                                'key' => 'apiv3_key',
                                'label' => 'API v3 Key',
                                'placeholder' => '请输入 APIv3 密钥',
                                'component' => 'password',
                                'required' => true,
                            ],
                            [
                                'key' => 'notify_url',
                                'label' => '支付回调地址',
                                'placeholder' => 'https://example.com/pay/notify',
                                'required' => true,
                            ],
                            [
                                'key' => 'refund_notify_url',
                                'label' => '退款回调地址',
                                'placeholder' => 'https://example.com/refund/notify',
                                'required' => true,
                            ],
                        ],
                    ],
                    'default' => [
                        'mchid' => '',
                        'app_id' => '',
                        'serial_no' => '',
                        'private_key' => '',
                        'apiv3_key' => '',
                        'notify_url' => '',
                        'refund_notify_url' => '',
                    ],
                    'sort' => 20,
                ],
                'mall.payment.balance_enabled' => [
                    'label' => '启用钱包支付',
                    'description' => '关闭后前台不会展示钱包通道。',
                    'type' => 'boolean',
                    'default' => true,
                    'sort' => 30,
                ],
                'mall.payment.balance_config' => [
                    'label' => '钱包支付配置',
                    'description' => '配置余额支付的展示名称、提示信息等。',
                    'type' => 'json',
                    'meta' => [
                        'component' => 'form',
                        'display' => 'dialog',
                        'trigger_key' => 'mall.payment.balance_enabled',
                        'trigger_value' => true,
                        'button_label' => '配置钱包',
                        'fields' => [
                            [
                                'key' => 'display_name',
                                'label' => '展示名称',
                                'placeholder' => '例如：商城钱包',
                                'required' => true,
                            ],
                            [
                                'key' => 'description',
                                'label' => '支付提示',
                                'component' => 'textarea',
                                'rows' => 3,
                                'placeholder' => '该文案会展示在前端支付方式说明中。',
                            ],
                            [
                                'key' => 'support_phone',
                                'label' => '客服电话',
                                'placeholder' => '400-000-0000',
                            ],
                        ],
                    ],
                    'default' => [
                        'display_name' => '钱包',
                        'description' => '',
                        'support_phone' => '',
                    ],
                    'sort' => 40,
                ],
                'mall.payment.refund_review' => [
                    'label' => '退款人工复核',
                    'description' => '开启后仅审核通过才调用支付网关退款接口。',
                    'type' => 'boolean',
                    'default' => true,
                    'sort' => 50,
                ],
                'mall.payment.settlement_cycle_days' => [
                    'label' => '结算周期（天）',
                    'description' => '商城内部对账、任务调度使用的周期配置。',
                    'type' => 'integer',
                    'default' => 7,
                    'sort' => 60,
                ],
            ],
        ],
        'shipping' => [
            'label' => '配送与物流',
            'description' => '快递、自提及第三方物流相关配置。',
            'sort' => 70,
            'settings' => [
                'mall.shipping.default_method' => [
                    'label' => '默认配送方式',
                    'description' => '用户下单默认选中的配送方式。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'select',
                        'options' => [
                            ['label' => '快递配送', 'value' => 'express'],
                            ['label' => '同城配送', 'value' => 'city'],
                            ['label' => '门店自提', 'value' => 'pickup'],
                        ],
                    ],
                    'default' => 'express',
                    'sort' => 10,
                ],
                'mall.shipping.enable_pickup' => [
                    'label' => '支持门店自提',
                    'description' => '开启后可在前台选择自提点。',
                    'type' => 'boolean',
                    'default' => true,
                    'sort' => 20,
                ],
                'mall.shipping.pickup_address' => [
                    'label' => '默认自提地址',
                    'description' => '当仅存在一个自提点时用于展示的地址信息。',
                    'type' => 'input',
                    'default' => '上海市浦东新区世纪大道 1000 号 L1 服务台',
                    'sort' => 30,
                ],
                'mall.shipping.free_shipping_threshold' => [
                    'label' => '包邮门槛',
                    'description' => '金额达到该值时免除运费，0 表示关闭。',
                    'type' => 'integer',
                    'default' => 100,
                    'sort' => 40,
                ],
                'mall.shipping.supported_providers' => [
                    'label' => '支持的快递公司',
                    'description' => '用于打印面单、订阅物流轨迹的白名单。',
                    'type' => 'json',
                    'meta' => [
                        'component' => 'tags',
                        'display_span' => ['compact'],
                        'placeholder' => '输入快递公司编码后回车添加',
                        'min_items' => 1,
                        'options' => [
                            ['label' => '顺丰速运 SF', 'value' => 'SF'],
                            ['label' => '京东物流 JD', 'value' => 'JD'],
                            ['label' => '圆通速递 YTO', 'value' => 'YTO'],
                            ['label' => '中通速递 ZTO', 'value' => 'ZTO'],
                            ['label' => '申通快递 STO', 'value' => 'STO'],
                        ],
                    ],
                    'default' => [
                        'SF',
                        'JD',
                        'YTO',
                    ],
                    'sort' => 50,
                ],
                'mall.shipping.default_freight_type' => [
                    'label' => '默认运费类型',
                    'description' => '商品未单独设置运费时的全局兜底策略。',
                    'type' => 'string',
                    'meta' => [
                        'component' => 'select',
                        'options' => [
                            ['label' => '全国包邮', 'value' => 'free'],
                            ['label' => '统一运费', 'value' => 'flat'],
                            ['label' => '运费模板', 'value' => 'template'],
                        ],
                    ],
                    'default' => 'free',
                    'sort' => 55,
                ],
                'mall.shipping.flat_freight_amount' => [
                    'label' => '统一运费金额',
                    'description' => '选择统一运费时的固定金额（单位：分）。',
                    'type' => 'json',
                    'is_sensitive' => true,
                    'meta' => [
                        'component' => 'form',
                        'display' => 'dialog',
                        'trigger_key' => 'mall.shipping.default_freight_type',
                        'trigger_value' => 'flat',
                        'button_label' => '配置运费',
                        'fields' => [
                            ['key' => 'amount', 'label' => '运费金额（分）', 'component' => 'number', 'required' => true],
                        ],
                    ],
                    'default' => ['amount' => 0],
                    'sort' => 56,
                ],
                'mall.shipping.remote_area_enabled' => [
                    'label' => '偏远地区加价',
                    'description' => '开启后对偏远地区收取额外运费。',
                    'type' => 'boolean',
                    'default' => false,
                    'sort' => 57,
                ],
                'mall.shipping.remote_area_surcharge' => [
                    'label' => '偏远地区加价配置',
                    'description' => '偏远地区额外运费和省份配置。',
                    'type' => 'json',
                    'meta' => [
                        'component' => 'form',
                        'display' => 'dialog',
                        'trigger_key' => 'mall.shipping.remote_area_enabled',
                        'trigger_value' => true,
                        'button_label' => '配置加价',
                        'fields' => [
                            ['key' => 'surcharge', 'label' => '加价金额（分）', 'component' => 'number', 'required' => true],
                            ['key' => 'provinces', 'label' => '偏远地区省份', 'component' => 'tags', 'required' => true,
                                'placeholder' => '输入省份名称后回车'],
                        ],
                    ],
                    'default' => [
                        'surcharge' => 0,
                        'provinces' => ['西藏', '新疆', '青海', '内蒙古', '宁夏', '甘肃'],
                    ],
                    'sort' => 58,
                ],

                'mall.shipping.default_template_config' => [
                    'label' => '默认运费模板',
                    'description' => '全局默认运费模板配置。',
                    'type' => 'json',
                    'meta' => [
                        'component' => 'form',
                        'display' => 'dialog',
                        'trigger_key' => 'mall.shipping.default_freight_type',
                        'trigger_value' => 'template',
                        'button_label' => '模板配置',
                        'fields' => [
                            ['key' => 'template_id', 'label' => '运费模板', 'component' => 'select', 'required' => true,
                                'description' => '选择已创建的运费模板'],
                        ],
                    ],
                    'default' => ['template_id' => 1],
                    'sort' => 61,
                ],
            ],
        ],
        'member' => [
            'label' => '会员与营销',
            'description' => '会员成长、积分和营销策略。',
            'sort' => 80,
            'settings' => [
                'mall.member.enable_growth' => [
                    'label' => '开启成长值',
                    'description' => '成长值用于升级会员等级与触发权益。',
                    'type' => 'boolean',
                    'default' => true,
                    'sort' => 10,
                ],
                'mall.member.register_points' => [
                    'label' => '注册赠送积分',
                    'description' => '新会员注册完成后赠送的积分数量。',
                    'type' => 'integer',
                    'default' => 100,
                    'sort' => 20,
                ],
                'mall.member.sign_in_reward' => [
                    'label' => '每日签到奖励',
                    'description' => '开启签到玩法后每日赠送的积分数量。',
                    'type' => 'integer',
                    'default' => 5,
                    'sort' => 30,
                ],
                'mall.member.invite_reward' => [
                    'label' => '邀请奖励积分',
                    'description' => '老会员邀请成功后额外获得的积分。',
                    'type' => 'integer',
                    'default' => 50,
                    'sort' => 40,
                ],
                'mall.member.points_expire_months' => [
                    'label' => '积分有效期（月）',
                    'description' => '到期后系统会定期清理失效积分。',
                    'type' => 'integer',
                    'default' => 24,
                    'sort' => 50,
                ],
                'mall.member.vip_levels' => [
                    'label' => '会员等级定义',
                    'description' => 'JSON 结构，用于约束等级门槛与权益。',
                    'type' => 'json',
                    'meta' => [
                        'component' => 'collection',
                        'display' => 'dialog',
                        'button_label' => '配置等级',
                        'min_items' => 1,
                        'max_items' => 5,
                        'add_label' => '新增等级',
                        'fields' => [
                            [
                                'key' => 'level',
                                'label' => '等级序号',
                                'component' => 'number',
                                'required' => true,
                                'min' => 1,
                            ],
                            [
                                'key' => 'name',
                                'label' => '等级名称',
                                'placeholder' => '如：银卡/金卡/黑金',
                                'required' => true,
                            ],
                            [
                                'key' => 'growth',
                                'label' => '成长值门槛',
                                'component' => 'number',
                                'required' => true,
                                'min' => 0,
                            ],
                        ],
                    ],
                    'default' => [
                        ['level' => 1, 'name' => '银卡', 'growth' => 0],
                        ['level' => 2, 'name' => '金卡', 'growth' => 2000],
                        ['level' => 3, 'name' => '黑金', 'growth' => 8000],
                    ],
                    'sort' => 60,
                ],
                'mall.member.default_level' => [
                    'label' => '默认会员等级',
                    'description' => '新会员注册后默认赋予的等级 ID。',
                    'type' => 'integer',
                    'default' => 1,
                    'sort' => 70,
                ],
                'mall.member.points_ratio' => [
                    'label' => '积分兑换比例',
                    'description' => '1 元可兑换的积分数量，用于积分抵现。',
                    'type' => 'integer',
                    'default' => 100,
                    'sort' => 80,
                ],
            ],
        ],
        'content' => [
            'label' => '内容与合规',
            'description' => '内容安全、隐私与监管相关配置。',
            'sort' => 90,
            'settings' => [
                'mall.content.prohibited_keywords' => [
                    'label' => '发布禁用词',
                    'description' => '命中的词语将直接拒绝提交，换行分隔。',
                    'type' => 'text',
                    'meta' => [
                        'display_span' => ['full'],
                    ],
                    'default' => "政治\n黄赌毒\n涉枪爆",
                    'sort' => 30,
                ],
                'mall.content.privacy_policy_url' => [
                    'label' => '隐私政策链接',
                    'description' => '用户注册、下单时展示的隐私条款链接。',
                    'type' => 'string',
                    'default' => '/pages/policies/privacy',
                    'sort' => 40,
                ],
                'mall.content.terms_url' => [
                    'label' => '用户协议链接',
                    'description' => '需跳转到最新的用户服务协议页面。',
                    'type' => 'string',
                    'default' => '/pages/policies/terms',
                    'sort' => 50,
                ],
                'mall.content.compliance_email' => [
                    'label' => '合规专用邮箱',
                    'description' => '涉及监管、投诉的邮件将统一流向该地址。',
                    'type' => 'string',
                    'default' => 'compliance@minemall.local',
                    'sort' => 60,
                ],
            ],
        ],
    ],
];
